/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RandomC */

#ifndef _Included_RandomC
#define _Included_RandomC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RandomC
 * Method:    getRandom
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_RandomC_getRandom
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
